meta_product_name: "Save Whey"
meta_title: "Save Whey - Promoções de Suplementos"
meta_description: "As melhores promoções de Suplementos Alimentares da internet!"
meta_image: "meta.png" # should exist in `app/assets/images/`